### ISSUE TITLE
could this boilerplate be updated?

### ISSUE THREAD

**Issue by edwmurph** [pcofilada/simple-react-native-starter#10]
I'm new to react native and am looking for a boilerplate with redux to get me started and this seems nice and minimal but currently doesn't work and is outdated.

Could you update this project?

**Comment by pcofilada** [comment]
Hello @edwmurph, maybe you can contribute on this boilerplate by sending pull request for updates. Since right now I'm a little busy to update this, but if I have a spare time I would love to update this.

**Comment by pcofilada** [comment]
I already updated all of the files and packages to newest version. Closing this for now.
